# Generated by Django 5.2.11 on 2026-02-25 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_category_slug_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discription',
            new_name='description',
        ),
    ]
