# Generated by Django 5.2.11 on 2026-03-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_rename_discription_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=500, unique=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(unique=True, upload_to='goods_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Цена'),
        ),
    ]
