# Generated by Django 5.2.11 on 2026-03-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(unique=True, upload_to='goods_images/', verbose_name='Изображение'),
        ),
    ]
