# Generated by Django 5.2.11 on 2026-03-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='temp-slug', max_length=255, unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
