"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Эта команда ищет файл .env и загружает переменные из него
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    
    # Мои приложения.
    'home',
    'goods',
    'carts',
    'users',
    'orders',


    # Сторонние библиотеки
    'django_cleanup.apps.CleanupConfig',
    'django_extensions',
    'easy_thumbnails',
    'widget_tweaks',
    

    
]


# Настройка, чтобы миниатюры (image) создавались правильно.
THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'easy_thumbnails.processors.scale_and_crop',
    'easy_thumbnails.processors.filters',
)


THUMBNAIL_QUALITY = 95  # Повышаем качество сжатия картинки
# Указываем подпапку для миниатюр, чтобы не было "мусора" в корне media
THUMBNAIL_SUBDIR = 'versions'


# Задайте «алиасы» (пресеты) в настройках для масштабирования image.
THUMBNAIL_ALIASES = {
    '': {
        'catalog_thumbnail': {
            'size': (500, 500), 
            'crop': False,          # ВАЖНО: Выключаем обрезку!
            'upscale': True,        # Растянуть мелкие до 180px
            'autocrop': True,       # УДАЛЯЕТ лишние белые поля вокруг банкир
            'quality': 95,          # Высокое качество сжатия
        },
        'detail_thumbnail': {
        'size': (700, 800),     #/* Увеличиваем размер для четкости на странице товара */
        'crop': False,          #/* Банка видна целиком */
        'upscale': True,        #/* Растягиваем мелкие исходники до 700px */
        'autocrop': True,       #/* КЛЮЧЕВАЯ СТРОКА: режет лишний фон в самом файле */
        'quality': 95           #/* Высокое качество картинки */

        },

    },
}




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]




ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',


                'carts.context_processors.cart_stats',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',

    # os.getenv будет подргружать из .env для 
    # безопасности чтобы секретные данные не оказались в github
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'), 
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]


# URL, по которому медиа-файлы будут доступны в браузере
MEDIA_URL = '/media/'

# Абсолютный путь в файловой системе, где будут лежать файлы
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Забудь про стандартного юзера, теперь главный — мой из приложения users
AUTH_USER_MODEL = 'users.User'



# os.getenv будет подргружать из .env  
REDIS_HOST = os.getenv('REDIS_HOST', 'redis')
REDIS_PORT = int(os.getenv('REDIS_PORT', '6379'))
