"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Эта команда ищет файл .env и загружает переменные из него
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    
    # Мои приложения.
    'home',
    'goods',
    'carts',
    'users',
    'orders',


    # Сторонние библиотеки
    'django_cleanup.apps.CleanupConfig',
    'django_extensions',
    'easy_thumbnails',
    'widget_tweaks',
    

    
]


# Настройка, чтобы миниатюры (image) создавались правильно.
THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'easy_thumbnails.processors.scale_and_crop',
    'easy_thumbnails.processors.filters',
)


THUMBNAIL_QUALITY = 95  # Повышаем качество сжатия картинки
# Указываем подпапку для миниатюр, чтобы не было "мусора" в корне media
THUMBNAIL_SUBDIR = 'versions'


# Задайте «алиасы» (пресеты) в настройках для масштабирования image.
THUMBNAIL_ALIASES = {
    '': {
        'catalog_thumbnail': {
            'size': (500, 500), 
            'crop': False,          # ВАЖНО: Выключаем обрезку!
            'upscale': True,        # Растянуть мелкие до 180px
            'autocrop': True,       # УДАЛЯЕТ лишние белые поля вокруг банкир
            'quality': 95,          # Высокое качество сжатия
        },
        'detail_thumbnail': {
        'size': (700, 800),     #/* Увеличиваем размер для четкости на странице товара */
        'crop': False,          #/* Банка видна целиком */
        'upscale': True,        #/* Растягиваем мелкие исходники до 700px */
        'autocrop': True,       #/* КЛЮЧЕВАЯ СТРОКА: режет лишний фон в самом файле */
        'quality': 95           #/* Высокое качество картинки */

        },

    },
}




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]




ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',


                'carts.context_processors.cart_stats',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ==============================================================================
#  1. ПОДКЛЮЧЕНИЕ К СУБД ЧЕРЕЗ ЖИВОЙ ЩИТ PGBOUNCER (ПОРТ 6432)
# ==============================================================================
DATABASES = {

    "default": {
        "ENGINE": "django.db.backends.postgresql",
        
        # Направляем сокеты на контейнер pgbouncer, а не на postgres напрямую!
        "HOST": os.getenv("PGBOUNCER_HOST", "pgbouncer"),
        
        # ПОРТ ПУЛЕРА: Бьет строго в порт шлюза 6432
        "PORT": int(os.getenv("PGBOUNCER_PORT", "6432")),
        
        "NAME": os.getenv("DB_NAME", "pharma_db"),
        "USER": os.getenv("DB_USER", "pharma_admin"),
        "PASSWORD": os.getenv("DB_PASSWORD", "secret_pass"),
        
        # ВНУТРЕННИЙ ПУЛ DJANGO (CONN_MAX_AGE):
        # Удерживает сокеты к PgBouncer "горячими" 10 минут (600 секунд), исключая оверхед на TCP-handshake.
        "CONN_MAX_AGE": 600,
        
        # НАСТРОЙКА СЕТЕВОГО СТЕКА ЯДРА LINUX (TCP KEEPALIVE)
        # Выжигает мертвые "зомби-соединения" из ОП и страхует от сетевых лагов внутри Docker.
        "OPTIONS": {
            "connect_timeout": 5,       # Разрыв попытки через 5 секунд простоя, если пулер перегружен
            "keepalives": 1,            # Включить нативную проверку пульса сокета на уровне ядра ОС
            "keepalives_idle": 30,      # Пинг сокета пустым пакетом через каждые 30 секунд простоя
            "keepalives_interval": 10,  # Интервал повторных пингов (каждые 10 секунд), если узел молчит 
            "keepalives_count": 5,      # Жесткое закрытие трубы, если после 5 пингов пулер не ответил
        }
    }
}
    

    # # os.getenv будет подргружать из .env для 
    # # безопасности чтобы секретные данные не оказались в github
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': os.getenv('DB_NAME'), 
    #     'USER': os.getenv('DB_USER'),
    #     'PASSWORD': os.getenv('DB_PASSWORD'),
    #     'HOST': os.getenv('DB_HOST'),
    #     'PORT': os.getenv('DB_PORT'),
    # }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]


# URL, по которому медиа-файлы будут доступны в браузере
MEDIA_URL = '/media/'

# Абсолютный путь в файловой системе, где будут лежать файлы
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Забудь про стандартного юзера, теперь главный — мой из приложения users
AUTH_USER_MODEL = 'users.User'


  



# ==============================================================================
#  ХАЙЛОД-МАГИСТРАЛИ В ОПЕРАТИВНУЮ ПАМЯТЬ REDIS (4 ИЗОЛИРОВАННЫХ ИНСТАНСА)
# ==============================================================================

#  ИНСТАНС 1: СЕЙФ КОРЗИН И ОСТАТКОВ (Порт 6379)
# Первичная истина для Lua-скриптов бронирования. Логирование изменений через Streams.
# os.getenv будет подргружать из .env
REDIS_CART_HOST = os.getenv('REDIS_CART_HOST', 'redis_cart')
REDIS_CART_PORT = int(os.getenv('REDIS_CART_PORT', '6379'))

#  ИНСТАНС 2: КЭШ ШАБЛОНОВ И ВЁРСТКИ HTML (Порт 6380)
# Стандартный кэш-движок Django для Server-Side Rendering страниц каталога Pharma.
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{os.getenv('REDIS_HTML_HOST', 'redis_html')}:{os.getenv('REDIS_HTML_PORT', '6380')}/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 50,         # Жесткий потолок сокетов к кэшу вёрстки
                "retry_on_timeout": True,      # Авто-повтор при микро-лагах сети Docker
            },
            "DECODE_RESPONSES": True,          # Строки выходят из кэша чистыми, а не байтами b''
        }
    }
}

# ИНСТАНС 3: БРОКЕР ФОНОВЫХ ОЧЕРЕДЕЙ CELERY (Порт 6381)
# Сюда Django выстреливает таски переоценки батчами и 15-минутный контроль брони.
CELERY_BROKER_URL = f"redis://{os.getenv('REDIS_CELERY_HOST', 'redis_celery')}:{os.getenv('REDIS_CELERY_PORT', '6381')}/0"
CELERY_RESULT_BACKEND = CELERY_BROKER_URL

# --- НАСТРОЙКИ НАДЕЖНОСТИ КОНВЕЙЕРА ОЧЕРЕДЕЙ ---
CELERY_TASK_ACKS_LATE = True                   # Задача стирается из ОП только ПОСЛЕ успешного выполнения Python-кода!
CELERY_TASK_REJECT_ON_WORKER_LOST = True       # Если воркер убил Linux-процесс, таска мгновенно возвращается в очередь.
CELERY_TASK_DEFAULT_RETRY_DELAY = 5            # Пауза в 5 секунд перед повтором при лаге СУБД или сети.
CELERY_TASK_MAX_RETRIES = 3                    # Максимум 3 попытки на задачу, чтобы не забить очередь вечным циклом.

# ИНСТАНС 4: ДВИЖОК КАТАЛОГА ТОВАРОВ И REDISEARCH (Порт 6382)
# Сюда мои таски льют свойства товаров, и отсюда RediSearch мгновенно выгребает поиск на тысячи юзеров.
REDIS_CATALOG_HOST = os.getenv('REDIS_CATALOG_HOST', 'redis_catalog')
REDIS_CATALOG_PORT = int(os.getenv('REDIS_CATALOG_PORT', '6382'))
