# Generated by Django 5.2.11 on 2026-07-02 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0002_alter_product_description_alter_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('delivery_address', models.TextField(verbose_name='Адрес доставки')),
                ('payment_method', models.CharField(choices=[('online', 'Онлайн-оплата на сайте'), ('cash_on_delivery', 'Оплата при получении (наличные)'), ('card_on_delivery', 'Оплата при получении (картой курьеру)')], default='online', max_length=30, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('requires_payment', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('in_delivery', 'В пути / Доставка'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='requires_payment', max_length=20, verbose_name='Статус заказа')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Статус оплаты')),
                ('idempotency_key', models.UUIDField(blank=True, null=True, unique=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'order',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название товара на момент покупки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена при покупке')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Проданный товар',
                'verbose_name_plural': 'Проданные товары',
                'db_table': 'order_item',
            },
        ),
    ]
