# Generated by Django 5.2.11 on 2026-07-04 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10, message='Введите подробный адрес доставки (минимум 10 символов).')], verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Неверный формат телефона. Используйте: +79999999999 или 89999999999', regex='^\\+?7\\d{10}$|^8\\d{10}$')], verbose_name='Номер телефона'),
        ),
    ]
