# Generated by Django 5.2.11 on 2026-07-06 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='idempotency_key',
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Неверный формат телефона. Используйте: +79999999999 или 89999999999', regex='^(?:\\+7|7|8)\\d{10}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена при покупке'),
        ),
    ]
